services:
  blue:
    build: .
    container_name: gembelfun_blue
    restart: unless-stopped
    ports:
      - "3000:80"

  green:
    build: .
    container_name: gembelfun_green
    restart: unless-stopped
    ports:
      - "3001:80"