// ============================================================
// HABBIT — data access layer.
// The ONLY module allowed to call `supabase.from(...)` / `.rpc(...)`
// for this app. Every function throws on error so callers use one
// try/catch instead of checking `.error` everywhere.
//
// Schema (see ../../setup.sql):
//   habbit_h — currently-running activities (deleted once stopped)
//   habbit_d — completed history (append-only)
// `supabase` is the global client created by ../../assets/supabaseClient.js
// (loaded as a classic <script> before this module).
// ============================================================
import { toTimeOfDay, toDateOnly, newId } from '../../assets/shared-utils.js';

const HIST_LIMIT = 500;

export async function fetchRunning(userId) {
  const { data, error } = await supabase
    .from('habbit_h')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });
  if (error) throw error;
  return data || [];
}

export async function fetchHistory(userId, limit = HIST_LIMIT) {
  const { data, error } = await supabase
    .from('habbit_d')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(limit);
  if (error) throw error;
  return data || [];
}

/**
 * Start a new RUNNING (timed, non-finance) activity. `activityId` is
 * generated by the caller (crypto.randomUUID()) and carried over to
 * habbit_d when this activity is eventually stopped, so the two rows
 * can be traced back to "the same activity" if ever needed.
 *
 * time_start/start_date are computed from the browser's own clock
 * (see toTimeOfDay/toDateOnly) rather than left to a DB default,
 * so they're correct in the user's real timezone.
 */
export async function startActivity({ userId, activityId, activity }) {
  const now = new Date();
  const payload = {
    user_id: userId,
    activity_id: activityId,
    activity,
    time_start: toTimeOfDay(now),
    start_date: toDateOnly(now),
  };
  const { data, error } = await supabase.from('habbit_h').insert(payload).select().single();
  if (error) throw error;
  return data;
}

/**
 * Record an expense ("Ini keluar duit"). Spending money isn't a
 * "running" state with something to stop later, so — unlike a timed
 * activity — this writes straight into habbit_d as an already-
 * complete, zero-duration row. Never touches habbit_h.
 */
export async function recordExpense({ userId, activity, financeTag, nominal }) {
  const now = new Date();
  const today = toDateOnly(now);
  const nowTime = toTimeOfDay(now);
  const payload = {
    user_id: userId,
    activity_id: newId(),
    activity,
    time_start: nowTime,
    time_end: nowTime,
    total_hours: 0,
    total_second: 0,
    finance_flag: true,
    finance_tag: financeTag || null,
    nominal,
    effective_date: today,
    start_date: today,
    end_date: today,
  };
  const { data, error } = await supabase.from('habbit_d').insert(payload).select().single();
  if (error) throw error;
  return data;
}

/**
 * Atomically move a habbit_h row into habbit_d via the stop_habbit
 * RPC (see setup.sql) — one DB transaction, so there's no window
 * where a client-side "insert then delete" could partially fail
 * and leave a duplicate or an orphan running row. Passes the
 * browser's own local time/date so the history row's end_date
 * lands on the correct calendar day for this user.
 */
export async function stopActivity(habbitHId) {
  const now = new Date();
  const { data, error } = await supabase.rpc('stop_habbit', {
    p_habbit_h_id: habbitHId,
    p_time_end: toTimeOfDay(now),
    p_end_date: toDateOnly(now),
  });
  if (error) throw error;
  return data;
}

/**
 * One realtime channel covering both tables for this user.
 * Returns an unsubscribe function.
 */
export function subscribeToChanges(userId, onChange) {
  const channel = supabase
    .channel('habbit-own-' + userId)
    .on('postgres_changes', { event: '*', schema: 'public', table: 'habbit_h', filter: `user_id=eq.${userId}` }, onChange)
    .on('postgres_changes', { event: '*', schema: 'public', table: 'habbit_d', filter: `user_id=eq.${userId}` }, onChange)
    .subscribe();
  return () => supabase.removeChannel(channel);
}
